### ISSUE TITLE
about text embedding 

### ISSUE THREAD

**Issue by Arlen-yuzu** [kywen1119/DSRAN#11]
请问在text embedding 中，由于句子长短的不同，不同sentence的word个数会不同，您的代码中貌似是采用了用0来padding的做法，这些padding对后续的GAT等网络会产生影响吗，或者说您是否考虑过这个问题？

**Comment by KevinLight831** [comment]
这是这个领域一脉相承的做法

**Comment by Arlen-yuzu** [comment]
我的意思是这些paidding得到的全0的词向量会不会成为GAT网络里面的噪声之类的

**Comment by KevinLight831** [comment]
maybe attention is all you need? maybe you can choose to trust the all-powerful transformer 😂 😂 😂 ，just kidding。
